language: node_js
node_js:
- '10'
branchs:
  only:
  - master
script:
- npm -v  
before_install:
- openssl aes-256-cbc -K $encrypted_e88bd3b6fb56_key -iv $encrypted_e88bd3b6fb56_iv
  -in id_rsa.enc -out ./id_rsa -d
after_success:
- ssh travis-ci@132.232.96.142 -o StrictHostKeyChecking=no 'cd /tmp && ls'